FROM node:23-slim

WORKDIR /app

# Copiar solo el package.json y package-lock.json para aprovechar la caché de Docker
COPY package*.json ./

# Instalar dependencias
RUN npm install

# Copiar el resto de la aplicación
COPY . .

# Exponer el puerto para la API
EXPOSE 4000

# Comando para iniciar el servidor
CMD ["node", "index.js"]